name: dotnet-sdk
version: 2.2.401
summary: Cross-Platform .NET Core SDK
description: |
  .NET Core SDK. https://dot.net/core.

grade: stable
confinement: classic

apps:
  dotnet:
    command: dotnet

base: core18

parts:
  dotnet-sdk:
      plugin: dump
      source: https://download.visualstudio.microsoft.com/download/pr/228832ea-805f-45ab-8c88-fa36165701b9/16ce29a06031eeb09058dee94d6f5330/dotnet-sdk-2.2.401-linux-x64.tar.gz
      source-checksum: sha512/08e1fcafa4f898c80ff5e88eeb40c7497b4f5651af3b8ec85f65a3daa2f1509a766d833477358d3ff83d179e014034ab0c48120847ef24736c8d1a5b67fec10b 
      stage-packages:
        - libicu60
        - libssl1.0.0
        - libcurl3
        - libgssapi-krb5-2
        - libstdc++6
        - zlib1g
        - libgcc1
        - lldb
        - libunwind8
        - libtinfo5
        - libc6
        - liblttng-ust0
        - liburcu6

  runtime-wrapper:
      plugin: dump
      source: .

